use crate::certification::sample_certifications;
use crate::halal::{evaluate_product, HalalStandard};
use crate::models::{
    CosingIngredient, HalalClassification, Product, ProductType, Retailer,
};
use chrono::Utc;
use uuid::Uuid;

pub fn sample_products() -> Vec<Product> {
    let mut products = vec![
        Product {
            id: Uuid::new_v4(),
            retailer: Retailer::Boots,
            retailer_sku: "BOOTS-001".into(),
            name: "Inika Organic Certified Lipstick - Nude".into(),
            brand: "Inika Organic".into(),
            image_url: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400".into(),
            category_path: "beauty/makeup/lips/lipstick".into(),
            product_type: ProductType::Makeup,
            sub_type: "lipstick".into(),
            ingredients_raw: Some("Ricinus Communis Seed Oil, Cera Alba, Iron Oxides, Tocopherol".into()),
            ingredients: vec![
                ing("Ricinus Communis Seed Oil"),
                ing("Cera Alba"),
                ing("Iron Oxides"),
                ing("Tocopherol"),
            ],
            halal_score: 0,
            halal_status: crate::models::HalalStatus::LikelyHalal,
            halal_flags: vec![],
            certifications: vec![sample_certifications()[0].clone()],
            price_gbp: Some(24.99),
            url: "https://www.boots.com/inika-organic-lipstick".into(),
            scraped_at: Utc::now(),
        },
        Product {
            id: Uuid::new_v4(),
            retailer: Retailer::Boots,
            retailer_sku: "BOOTS-002".into(),
            name: "MAC Retro Matte Lipstick - Ruby Woo".into(),
            brand: "MAC".into(),
            image_url: "https://images.unsplash.com/photo-1631214524020-7e146d04b45b?w=400".into(),
            category_path: "beauty/makeup/lips/lipstick".into(),
            product_type: ProductType::Makeup,
            sub_type: "lipstick".into(),
            ingredients_raw: Some("Ricinus Communis Seed Oil, Carmine (CI 75470), Cera Alba, Tocopherol".into()),
            ingredients: vec![
                ing("Ricinus Communis Seed Oil"),
                ing("Carmine (CI 75470)"),
                ing("Cera Alba"),
                ing("Tocopherol"),
            ],
            halal_score: 0,
            halal_status: crate::models::HalalStatus::LikelyHalal,
            halal_flags: vec![],
            certifications: vec![],
            price_gbp: Some(19.50),
            url: "https://www.boots.com/mac-ruby-woo".into(),
            scraped_at: Utc::now(),
        },
        Product {
            id: Uuid::new_v4(),
            retailer: Retailer::Superdrug,
            retailer_sku: "SD-003".into(),
            name: "Wardah Lightening Liquid Foundation".into(),
            brand: "Wardah".into(),
            image_url: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400".into(),
            category_path: "beauty/makeup/face/foundation".into(),
            product_type: ProductType::Makeup,
            sub_type: "foundation".into(),
            ingredients_raw: Some("Aqua, Glycerin, Niacinamide, Tocopherol, Panthenol".into()),
            ingredients: vec![
                ing("Aqua"),
                ing("Glycerin"),
                ing("Niacinamide"),
                ing("Tocopherol"),
                ing("Panthenol"),
            ],
            halal_score: 0,
            halal_status: crate::models::HalalStatus::LikelyHalal,
            halal_flags: vec![],
            certifications: vec![sample_certifications()[1].clone()],
            price_gbp: Some(12.99),
            url: "https://www.superdrug.com/wardah-foundation".into(),
            scraped_at: Utc::now(),
        },
        Product {
            id: Uuid::new_v4(),
            retailer: Retailer::Boots,
            retailer_sku: "BOOTS-004".into(),
            name: "Chanel No. 5 Eau de Parfum".into(),
            brand: "Chanel".into(),
            image_url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400".into(),
            category_path: "beauty/fragrance/womens-perfume".into(),
            product_type: ProductType::Fragrance,
            sub_type: "eau-de-parfum".into(),
            ingredients_raw: Some("Alcohol Denat., Parfum, Aqua, Benzyl Salicylate, Linalool".into()),
            ingredients: vec![
                ing("Alcohol Denat."),
                ing("Parfum"),
                ing("Aqua"),
                ing("Benzyl Salicylate"),
                ing("Linalool"),
            ],
            halal_score: 0,
            halal_status: crate::models::HalalStatus::LikelyHalal,
            halal_flags: vec![],
            certifications: vec![],
            price_gbp: Some(105.00),
            url: "https://www.boots.com/chanel-no5".into(),
            scraped_at: Utc::now(),
        },
        Product {
            id: Uuid::new_v4(),
            retailer: Retailer::Boots,
            retailer_sku: "BOOTS-005".into(),
            name: "PHB Ethical Beauty Mineral Foundation".into(),
            brand: "PHB Ethical Beauty".into(),
            image_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400".into(),
            category_path: "beauty/makeup/face/foundation".into(),
            product_type: ProductType::Makeup,
            sub_type: "foundation".into(),
            ingredients_raw: Some("Mica, Zinc Oxide, Iron Oxides, Jojoba Seed Oil, Tocopherol".into()),
            ingredients: vec![
                ing("Mica"),
                ing("Zinc Oxide"),
                ing("Iron Oxides"),
                ing("Simmondsia Chinensis Seed Oil"),
                ing("Tocopherol"),
            ],
            halal_score: 0,
            halal_status: crate::models::HalalStatus::LikelyHalal,
            halal_flags: vec![],
            certifications: vec![sample_certifications()[2].clone()],
            price_gbp: Some(18.95),
            url: "https://www.boots.com/phb-mineral-foundation".into(),
            scraped_at: Utc::now(),
        },
        Product {
            id: Uuid::new_v4(),
            retailer: Retailer::Superdrug,
            retailer_sku: "SD-006".into(),
            name: "Olaplex No.3 Hair Perfector".into(),
            brand: "Olaplex".into(),
            image_url: "https://images.unsplash.com/photo-1527799820374-dcf8d9a5e3f0?w=400".into(),
            category_path: "beauty/haircare/treatments".into(),
            product_type: ProductType::Haircare,
            sub_type: "treatments".into(),
            ingredients_raw: Some("Aqua, Bis-Aminopropyl Diglycol Dimaleate, Phenoxyethanol, Sodium Benzoate".into()),
            ingredients: vec![
                ing("Aqua"),
                ing("Bis-Aminopropyl Diglycol Dimaleate"),
                ing("Phenoxyethanol"),
                ing("Sodium Benzoate"),
            ],
            halal_score: 0,
            halal_status: crate::models::HalalStatus::LikelyHalal,
            halal_flags: vec![],
            certifications: vec![],
            price_gbp: Some(28.00),
            url: "https://www.superdrug.com/olaplex-no3".into(),
            scraped_at: Utc::now(),
        },
        Product {
            id: Uuid::new_v4(),
            retailer: Retailer::Boots,
            retailer_sku: "BOOTS-007".into(),
            name: "Herbal Essences Argan Oil Shampoo".into(),
            brand: "Herbal Essences".into(),
            image_url: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400".into(),
            category_path: "beauty/haircare/shampoo".into(),
            product_type: ProductType::Haircare,
            sub_type: "shampoo".into(),
            ingredients_raw: Some("Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Argania Spinosa Kernel Oil, Glycerin".into()),
            ingredients: vec![
                ing("Aqua"),
                ing("Sodium Laureth Sulfate"),
                ing("Cocamidopropyl Betaine"),
                ing("Argania Spinosa Kernel Oil"),
                ing("Glycerin"),
            ],
            halal_score: 0,
            halal_status: crate::models::HalalStatus::LikelyHalal,
            halal_flags: vec![],
            certifications: vec![],
            price_gbp: Some(3.50),
            url: "https://www.boots.com/herbal-essences-shampoo".into(),
            scraped_at: Utc::now(),
        },
        Product {
            id: Uuid::new_v4(),
            retailer: Retailer::LookFantastic,
            retailer_sku: "LF-008".into(),
            name: "MCoBeauty XtendLash Mascara".into(),
            brand: "MCoBeauty".into(),
            image_url: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400".into(),
            category_path: "beauty/makeup/eyes/mascara".into(),
            product_type: ProductType::Makeup,
            sub_type: "mascara".into(),
            ingredients_raw: Some("Aqua, Cera Alba, Iron Oxides, Panthenol, Tocopherol".into()),
            ingredients: vec![
                ing("Aqua"),
                ing("Cera Alba"),
                ing("Iron Oxides"),
                ing("Panthenol"),
                ing("Tocopherol"),
            ],
            halal_score: 0,
            halal_status: crate::models::HalalStatus::LikelyHalal,
            halal_flags: vec![],
            certifications: vec![sample_certifications()[3].clone()],
            price_gbp: Some(15.00),
            url: "https://www.lookfantastic.com/mcobeauty-mascara".into(),
            scraped_at: Utc::now(),
        },
    ];

    for product in &mut products {
        evaluate_product(product, HalalStandard::Strict);
    }

    products
}

fn ing(name: &str) -> CosingIngredient {
    CosingIngredient {
        inci_name: name.into(),
        slug: None,
        cas_number: None,
        ec_number: None,
        functions: vec![],
        restriction: None,
        halal_classification: HalalClassification::Halal,
    }
}
